server:
  port: 8085
grpc:
  server:
    port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/point_system_db
    username: jahid
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  data: classpath:data.sql
  schema: classpath:schema.sql

