CREATE TABLE payment_methods (
id BIGINT PRIMARY KEY,
name VARCHAR(20) NOT NULL,
point_rate FLOAT NOT NULL,
additional_info VARCHAR(100)
);

CREATE TABLE payments (
id BIGINT PRIMARY KEY,
customer_id VARCHAR(10) NOT NULL,
price FLOAT NOT NULL,
price_modifier FLOAT NOT NULL,
final_price FLOAT NOT NULL,
points FLOAT NOT NULL,
purchase_date TIMESTAMP WITH TIME ZONE NOT NULL,
payment_method_id BIGINT NOT NULL,
FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id)
);

CREATE TABLE card_details (
id BIGINT PRIMARY KEY,
card_number VARCHAR(4) NOT NULL,
payment_id BIGINT NOT NULL,
FOREIGN KEY (payment_id) REFERENCES payments(id)
);

CREATE TABLE bank_details (
id BIGINT PRIMARY KEY,
bank_name VARCHAR(100) NOT NULL,
account_number VARCHAR(20) NOT NULL,
payment_id BIGINT NOT NULL,
FOREIGN KEY (payment_id) REFERENCES payments(id)
);

CREATE TABLE cheque_details (
id BIGINT PRIMARY KEY,
bank_name VARCHAR(100) NOT NULL,
cheque_number VARCHAR(20) NOT NULL,
payment_id BIGINT NOT NULL,
FOREIGN KEY (payment_id) REFERENCES payments(id)
);

CREATE TABLE courier_services (
id BIGINT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
permitted BOOLEAN DEFAULT TRUE
);

CREATE SEQUENCE bank_details_seq START WITH 1 INCREMENT BY 1 NO CYCLE;
CREATE SEQUENCE card_details_seq START WITH 1 INCREMENT BY 1 NO CYCLE;
CREATE SEQUENCE cheque_details_seq START WITH 1 INCREMENT BY 1 NO CYCLE;
CREATE SEQUENCE courier_services_seq START WITH 1 INCREMENT BY 1 NO CYCLE;
CREATE SEQUENCE payment_seq START WITH 1 INCREMENT BY 1 NO CYCLE;
CREATE SEQUENCE payment_methods_seq START WITH 1 INCREMENT BY 1 NO CYCLE;